[package]
name = "algorithm"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.2"
[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }
[[bench]]
name = "longest_subsequence_bench"
harness = false
