[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
hmac = "0.12"
k256 = { version = "0.13", features = ["ecdsa"] }
rand = "0.8"
thiserror = "2.0"

[dev-dependencies]
hex = "0.4"
